language: python
python:
  - "3.8"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - py.test .
after-sucess:
  - if [[ $ENV == python=3.8* ]]; then
      coveralls;
    fi